---
extends:
- standard
- standard-react
parser: babel-eslint
env:
  browser: true
  node: true
rules:
  react/prop-types:
  - warn
  - skipUndeclared: true
  linebreak-style:
  - error
  - unix
  max-len:
  - error
  - 90
  max-lines:
  - warn
  - 400
